[project]
name = "zentao-pms"
version = "12.4.2"
vendor = "zentao.net"
homepage = "http://www.zentao.net"
description = "Project management"
groups = ["app/co", "app/dev"]

[files]

[scripts]
build = """
cd {{.inpack__pack_dir}}/deps

if [ ! -f "ZenTaoPMS.{{.project__version}}.zip" ]; then
    wget http://dl.cnezsoft.com/zentao/{{.project__version}}/ZenTaoPMS.{{.project__version}}.zip
fi

if [ ! -d "zentaopms" ]; then
    unzip ZenTaoPMS.{{.project__version}}.zip
fi

rsync -av zentaopms/* {{.buildroot}}/

rm -rf zentaopms
mkdir -p {{.buildroot}}/misc/zentao-pms
cd {{.inpack__pack_dir}}

cp -rp misc/zentao-pms/config__my.php {{.buildroot}}/misc/zentao-pms/config__my.php
cp -rp misc/zentao-pms/module__install__view__step2.html.php {{.buildroot}}/misc/zentao-pms/module__install__view__step2.html.php
cp -rp misc/zentao-pms/www__index.php {{.buildroot}}/misc/zentao-pms/www__index.php

install misc/zentao-pms/www__index.php {{.buildroot}}/www/index.php
"""

